from dataclasses import dataclass, field

@dataclass
class AccountInstance:
    """
    A local facility instance, not dependent on the database.
    """

    # Account creation
    # UUID is generated by the database
    username: str
    email: str
    pass_hash: str  # blah
    registered_on: str
    last_login: str
